# Generated by Django 4.2.8 on 2023-12-19 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "research_area",
                    models.CharField(
                        blank=True, default="請輸入您的研究領域", max_length=100, null=True
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, default="請輸入您的最高學歷", max_length=100, null=True
                    ),
                ),
                (
                    "key_skills",
                    models.CharField(
                        blank=True, default="請輸入您的專業技能", max_length=100, null=True
                    ),
                ),
                (
                    "work_experiences",
                    models.CharField(
                        blank=True, default="請輸入您的工作經驗", max_length=100, null=True
                    ),
                ),
                (
                    "relevant_coursework",
                    models.CharField(
                        blank=True, default="請輸入您的相關課程", max_length=100, null=True
                    ),
                ),
                (
                    "extracurricular",
                    models.CharField(
                        blank=True, default="請輸入您的課外活動", max_length=100, null=True
                    ),
                ),
                (
                    "language_skills",
                    models.CharField(
                        blank=True, default="請輸入您的外語能力", max_length=100, null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=1000)),
                ("answer", models.TextField()),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
