# Generated by Django 4.2.8 on 2023-12-15 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0002_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="chatapp.student",
            ),
        ),
    ]
