# Generated by Django 4.2.8 on 2023-12-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0004_userextenstion_alter_questionanswer_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserExtenstion",
        ),
    ]
