# Generated by Django 5.0 on 2023-12-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
