# Generated by Django 5.0 on 2023-12-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_remove_userprofile_avatar_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='additional_field',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='research_area',
            field=models.CharField(blank=True, default='輸入您的研究領域', max_length=100, null=True),
        ),
    ]
