# Generated by Django 5.0 on 2023-12-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_remove_userprofile_additional_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True, default='請輸入您的最高學歷', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extracurricular',
            field=models.CharField(blank=True, default='請輸入您的課外活動', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='key_skills',
            field=models.CharField(blank=True, default='請輸入您的專業技能', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language_skills',
            field=models.CharField(blank=True, default='請輸入您的外語能力', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relevant_coursework',
            field=models.CharField(blank=True, default='請輸入您的相關課程', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_experiences',
            field=models.CharField(blank=True, default='請輸入您的工作機會', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='research_area',
            field=models.CharField(blank=True, default='請輸入您的研究領域', max_length=100, null=True),
        ),
    ]
